"""Paper Trading Dashboard v1.

Run from the project src folder with:
    streamlit run paper_trading_dashboard_v1.py

The dashboard reads the CSV files generated by paper_trader_v3_position_manager.py.
It never places orders and does not modify trading state.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import pandas as pd
import streamlit as st


APP_TITLE = "Market Regime Risk Engine"
DEFAULT_MARKET = "ETC-USD"
REFRESH_SECONDS = 60


@st.cache_data(ttl=REFRESH_SECONDS)
def read_csv_safe(path: Path) -> pd.DataFrame:
    """Read a CSV without crashing when the file is missing or empty."""
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except (pd.errors.EmptyDataError, pd.errors.ParserError, OSError):
        return pd.DataFrame()


def first_existing_value(row: pd.Series, names: list[str], default: object = None) -> object:
    """Return the first non-null value found under any candidate column name."""
    for name in names:
        if name in row.index and pd.notna(row[name]):
            return row[name]
    return default


def as_number(value: object) -> Optional[float]:
    try:
        if value is None or pd.isna(value):
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def format_price(value: object) -> str:
    number = as_number(value)
    return "—" if number is None else f"${number:,.4f}"


def format_r(value: object) -> str:
    number = as_number(value)
    return "—" if number is None else f"{number:+.2f}R"


def format_timestamp(value: object) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "—"
    parsed = pd.to_datetime(value, errors="coerce", utc=True)
    if pd.isna(parsed):
        return str(value)
    return parsed.strftime("%Y-%m-%d %H:%M UTC")


def latest_row(df: pd.DataFrame) -> Optional[pd.Series]:
    if df.empty:
        return None
    return df.iloc[-1]


def find_open_position(positions: pd.DataFrame) -> Optional[pd.Series]:
    if positions.empty:
        return None

    status_column = next(
        (name for name in ["status", "position_status", "trade_status"] if name in positions.columns),
        None,
    )
    if status_column is None:
        return positions.iloc[-1]

    open_rows = positions[
        positions[status_column].astype(str).str.upper().isin(["OPEN", "ACTIVE"])
    ]
    return None if open_rows.empty else open_rows.iloc[-1]


def trade_summary(trades: pd.DataFrame) -> dict[str, float]:
    if trades.empty:
        return {
            "count": 0,
            "win_rate": 0.0,
            "total_r": 0.0,
            "average_r": 0.0,
        }

    r_column = next(
        (name for name in ["r_multiple", "result_r", "realized_r"] if name in trades.columns),
        None,
    )
    if r_column is None:
        return {
            "count": len(trades),
            "win_rate": 0.0,
            "total_r": 0.0,
            "average_r": 0.0,
        }

    values = pd.to_numeric(trades[r_column], errors="coerce").dropna()
    if values.empty:
        return {
            "count": len(trades),
            "win_rate": 0.0,
            "total_r": 0.0,
            "average_r": 0.0,
        }

    return {
        "count": int(len(values)),
        "win_rate": float((values > 0).mean() * 100),
        "total_r": float(values.sum()),
        "average_r": float(values.mean()),
    }


def main() -> None:
    st.set_page_config(page_title=APP_TITLE, page_icon="📈", layout="wide")

    project_root = Path(__file__).resolve().parent
    analysis_dir = project_root / "analysis"

    signal_path = analysis_dir / "paper_trade_signal_log_BAD_BACKUP.csv"
    position_path = analysis_dir / "paper_trade_position_state.csv"
    trades_path = analysis_dir / "paper_trade_trades.csv"

    signals = read_csv_safe(signal_path)
    positions = read_csv_safe(position_path)
    trades = read_csv_safe(trades_path)

    st.title(APP_TITLE)
    st.caption(
        "Paper-trading monitor for live signals, position state, and simulated performance. "
        "Real orders are disabled."
    )

    latest_signal = latest_row(signals)
    open_position = find_open_position(positions)
    summary = trade_summary(trades)

    if latest_signal is None:
        market = DEFAULT_MARKET
        regime = "—"
        decision = "No signal data"
        edge_score = "—"
        latest_close = "—"
        latest_time = "—"
    else:
        market = str(first_existing_value(latest_signal, ["market", "ticker"], DEFAULT_MARKET))
        regime = str(first_existing_value(latest_signal, ["regime", "market_regime"], "—"))
        decision = str(
            first_existing_value(
                latest_signal,
                ["final_decision", "decision", "raw_decision"],
                "—",
            )
        )
        edge_value = first_existing_value(latest_signal, ["edge_score", "score"], None)
        edge_number = as_number(edge_value)
        edge_score = "—" if edge_number is None else f"{edge_number:.0f}"
        latest_close = format_price(first_existing_value(latest_signal, ["close", "price"], None))
        latest_time = format_timestamp(
            first_existing_value(latest_signal, ["candle_time", "timestamp", "datetime"], None)
        )

    top_cols = st.columns(6)
    top_cols[0].metric("Market", market)
    top_cols[1].metric("Regime", regime)
    top_cols[2].metric("Decision", decision)
    top_cols[3].metric("Edge Score", edge_score)
    top_cols[4].metric("Latest Close", latest_close)
    top_cols[5].metric("Last Candle", latest_time)

    st.divider()

    left, right = st.columns([1, 1])

    with left:
        st.subheader("Open Position")
        if open_position is None:
            st.info("No open paper position.")
        else:
            direction = str(
                first_existing_value(open_position, ["direction", "side", "trade_side"], "—")
            )
            status = str(
                first_existing_value(open_position, ["status", "position_status"], "OPEN")
            )
            entry = first_existing_value(open_position, ["entry_price", "entry"], None)
            stop = first_existing_value(open_position, ["stop_price", "stop"], None)
            target = first_existing_value(
                open_position, ["target_price", "tp_price", "target", "take_profit"], None
            )
            current_r = first_existing_value(
                open_position, ["unrealized_r", "current_r", "r_multiple"], None
            )
            opened = first_existing_value(
                open_position, ["open_time", "entry_time", "opened_at"], None
            )

            position_cols = st.columns(3)
            position_cols[0].metric("Direction", direction)
            position_cols[1].metric("Status", status)
            position_cols[2].metric("Current P/L", format_r(current_r))

            details = pd.DataFrame(
                {
                    "Field": ["Entry", "Stop", "Target", "Opened"],
                    "Value": [
                        format_price(entry),
                        format_price(stop),
                        format_price(target),
                        format_timestamp(opened),
                    ],
                }
            )
            st.dataframe(details, hide_index=True, use_container_width=True)

    with right:
        st.subheader("Paper Performance")
        perf_cols = st.columns(4)
        perf_cols[0].metric("Closed Trades", summary["count"])
        perf_cols[1].metric("Win Rate", f"{summary['win_rate']:.1f}%")
        perf_cols[2].metric("Total R", f"{summary['total_r']:+.2f}R")
        perf_cols[3].metric("Average R", f"{summary['average_r']:+.2f}R")

        if not trades.empty:
            st.dataframe(trades.tail(10), hide_index=True, use_container_width=True)
        else:
            st.info("No closed paper trades yet.")

    st.divider()
    st.subheader("Recent Signal Checks")
    if signals.empty:
        st.warning(
            "No signal log found yet. Run paper_trader_v3_position_manager.py first."
        )
    else:
        st.dataframe(signals.tail(20).iloc[::-1], hide_index=True, use_container_width=True)

    with st.expander("Data files"):
        st.code(
            "\n".join(
                [
                    f"Signal log:    {signal_path}",
                    f"Position:      {position_path}",
                    f"Trade history: {trades_path}",
                ]
            )
        )

    st.caption(
        "Refresh the browser after running the position manager, or wait up to "
        f"{REFRESH_SECONDS} seconds for cached data to expire."
    )


if __name__ == "__main__":
    main()
